---
jobs:
  - job: "Run_bot"
    pool:
      vmImage: 'vs2017-win2016'
    strategy:
      matrix:
        Python37:
          python.version: '3.7'
      maxParallel: 1

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: $(python.version)
          architecture: x64

      - script: "pip install selenium && pip install requests && pip install twilio && npm -g install chromedriver@75.0.0"
        displayName: "Install dependencies"

      - powershell: "python TipBot.py"
        displayName: "Run tipping bot."
        env:
          EMAIL: $(email)
          PASSWORD: $(password)
          CHROMEDRIVER: $(chromedriver)
          TWILIO_ACCOUNT_SID: $(twilio_account_sid)
          TWILIO_AUTH_TOKEN: $(twilio_auth_token)
schedules:
- cron: "0 12 * * 3"
  displayName: Weekly Wednesday build
  branches:
    include:
    - master
  always: true

trigger:
  - master
